In [4]:
import sqlite3
from pandas import read_sql

conn = sqlite3.connect('C:\code\python projects\encost\\testDB.db', check_same_thread=False)
df_main = read_sql('SELECT * FROM sources', conn)
print(df_main)
conn.close()
# [235 rows x 20 columns]

         client_name  endpoint_id  endpoint_name   shift_day calendar_day
0    Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-12  \
1    Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-12
2    Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-12
3    Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-12
4    Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-12
..               ...          ...            ...         ...          ...
230  Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-13
231  Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-13
232  Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-13
233  Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-13
234  Кирпичный Завод         2007  Бетономешалка  2023-05-12   2023-05-13

          state     status              reason              state_begin
0       Простой  Не работа  Причина не указана  2023-05-12 08:00:00.000  \
1    Вычисление  Не работа          Вычисление  2023-05-12 08:02:15.000
2       Простой  Не работа  Короткая остановка  2023-05-12 08:02:17.000
3       Простой  Не работа  Короткая остановка  2023-05-12 08:03:04.000
4    Вычисление  Не работа          Вычисление  2023-05-12 08:13:07.000
..          ...        ...                 ...                      ...
230      Работа     Работа              Работа  2023-05-13 07:14:56.000
231     Простой  Не работа  Короткая остановка  2023-05-13 07:18:12.000
232      Работа     Работа              Работа  2023-05-13 07:22:03.000
233      Работа     Работа              Работа  2023-05-13 07:59:08.000
234      Работа     Работа              Работа  2023-05-13 07:59:19.000

                   state_end  duration_hour  duration_min    color
0    2023-05-12 08:02:15.000       0.037500      2.250000  #ed1c09  \
1    2023-05-12 08:02:17.000       0.000556      0.033333  #3d0a42
2    2023-05-12 08:03:04.000       0.013056      0.783333  #e0827b
3    2023-05-12 08:13:07.000       0.167500     10.050000  #e0827b
4    2023-05-12 08:13:08.000       0.000278      0.016667  #3d0a42
..                       ...            ...           ...      ...
230  2023-05-13 07:18:12.000       0.054444      3.266667  #2ecc40
231  2023-05-13 07:22:03.000       0.064167      3.850000  #e0827b
232  2023-05-13 07:59:08.000       0.618056     37.083333  #2ecc40
233  2023-05-13 07:59:19.000       0.003056      0.183333  #2ecc40
234  2023-05-13 08:00:00.000       0.011389      0.683333  #2ecc40

    period_name shift_name       operator      operator_auth_start
0       Дневная    Дневная  Артемьев А.Б.  2023-05-11 20:11:02.000  \
1       Дневная    Дневная  Артемьев А.Б.  2023-05-11 20:11:02.000
2       Дневная    Дневная  Артемьев А.Б.  2023-05-11 20:11:02.000
3       Дневная    Дневная  Артемьев А.Б.  2023-05-11 20:11:02.000
4       Дневная    Дневная     Мухин Ч.В.  2023-05-12 08:13:07.000
..          ...        ...            ...                      ...
230      Ночная     Ночная   Донской У.М.  2023-05-12 20:16:37.000
231      Ночная     Ночная   Донской У.М.  2023-05-12 20:16:37.000
232      Ночная     Ночная   Донской У.М.  2023-05-12 20:16:37.000
233      Ночная     Ночная   Донской У.М.  2023-05-12 20:16:37.000
234      Ночная     Ночная   Донской У.М.  2023-05-12 20:16:37.000

           operator_auth_end shift_begin shift_end
0    2023-05-12 08:13:07.000    08:00:00  20:00:00
1    2023-05-12 08:13:07.000    08:00:00  20:00:00
2    2023-05-12 08:13:07.000    08:00:00  20:00:00
3    2023-05-12 08:13:07.000    08:00:00  20:00:00
4    2023-05-12 19:05:30.000    08:00:00  20:00:00
..                       ...         ...       ...
230                     None    08:00:00  20:00:00
231                     None    08:00:00  20:00:00
232                     None    08:00:00  20:00:00
233                     None    08:00:00  20:00:00
234                     None    08:00:00  20:00:00

[235 rows x 20 columns]

In [5]:
import sqlite3
from pandas import read_sql

conn = sqlite3.connect('C:\code\python projects\encost\\testDB.db', check_same_thread=False)
df_main = read_sql('SELECT reason, color FROM sources GROUP BY reason', conn)
print(df_main)
conn.close()

                           reason    color
0                      Вычисление  #3d0a42
1             Заточка инструмента  #eac117
2              Короткая остановка  #e0827b
3                         Наладка  #4169e1
4                      Обед 30мин  #bcb88a
5                      Обед 60мин  #bcb88a
6                    Перерыв 5мин  #FF8C00
7    Подготовка к выполнению см/з  #ff00ff
8                 Поиск заготовок  #e77474
9              Причина не указана  #ed1c09
10                         Работа  #2ecc40
11             Слесарная операция  #af9b84
12          См. задание выполнено  #cd5c5c
13  Тех.обслуживание оборудования  #4169e4

In [6]:
import sqlite3
from pandas import read_sql

conn = sqlite3.connect('C:\code\python projects\encost\\testDB.db', check_same_thread=False)
df_main = read_sql('SELECT reason, SUM(duration_min) FROM sources GROUP BY reason', conn)
print(df_main)
conn.close()

                           reason  SUM(duration_min)
0                      Вычисление           0.350000
1             Заточка инструмента          13.833333
2              Короткая остановка         229.800000
3                         Наладка         133.166667
4                      Обед 30мин          12.466667
5                      Обед 60мин          60.100000
6                    Перерыв 5мин          22.433333
7    Подготовка к выполнению см/з          15.466667
8                 Поиск заготовок          29.983333
9              Причина не указана          53.300000
10                         Работа         763.216667
11             Слесарная операция          25.700000
12          См. задание выполнено          64.000000
13  Тех.обслуживание оборудования          16.183333